# Generated by Django 6.0.5 on 2026-06-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0002_add_formdraft_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Đã nộp'), ('cancelled', 'Đã hủy')], default='submitted', max_length=20),
        ),
    ]
