# Generated by Django 6.0.5 on 2026-06-28 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0003_add_status_to_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='checker_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='manager_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='status',
            field=models.CharField(choices=[('pending_checker', 'Chờ Checker duyệt'), ('pending_manager', 'Chờ Manager duyệt'), ('approved', 'Đã phê duyệt'), ('rejected', 'Bị từ chối'), ('cancelled', 'Đã hủy')], default='pending_checker', max_length=20),
        ),
    ]
