# Generated by Django 6.0.5 on 2026-06-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0004_update_submission_for_rbac_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='status',
            field=models.CharField(choices=[('pending_checker', 'Chờ Checker duyệt'), ('pending_manager', 'Chờ Manager duyệt'), ('approved', 'Đã phê duyệt'), ('rejected', 'Bị từ chối'), ('cancelled', 'Đã hủy (Lúc chưa duyệt)'), ('pending_cancel_checker', 'Xin hủy - Chờ Checker'), ('pending_cancel_manager', 'Xin hủy - Chờ Manager'), ('revoked', 'Tài liệu đã hủy')], default='pending_checker', max_length=50),
        ),
    ]
